/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CharacterProfile = IDL.Record({
  'audioVolume' : IDL.Nat,
  'name' : IDL.Text,
  'archetype' : IDL.Text,
  'cosmeticOptions' : IDL.Vec(IDL.Text),
  'basicStats' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerCharacterProfile' : IDL.Func(
      [],
      [IDL.Opt(CharacterProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CharacterProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCharacterProfile' : IDL.Func([CharacterProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CharacterProfile = IDL.Record({
    'audioVolume' : IDL.Nat,
    'name' : IDL.Text,
    'archetype' : IDL.Text,
    'cosmeticOptions' : IDL.Vec(IDL.Text),
    'basicStats' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerCharacterProfile' : IDL.Func(
        [],
        [IDL.Opt(CharacterProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CharacterProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCharacterProfile' : IDL.Func([CharacterProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };